
#pragma once

#include < algorithm >
#include < array >
#include < atomic >
#include < bitset >
#include < cassert >
#include < cctype >
#include < cerrno >
#include < cfenv >
#include < cfloat >
#include < chrono >
#include < cinttypes >
#include < ciso646 >
#include < climits >
#include < clocale >
#include < cmath >
#include < codecvt >
#include < complex >
#include < condition_variable >
#include < csetjmp >
#include < csignal >
#include < cstdarg >
#include < cstddef >
#include < cstdint >
#include < cstdio >
#include < cstdlib >
#include < cstring >
#include < ctime >
#include < cuchar >
#include < cwchar >
#include < cwctype >
#include < deque >
#include < exception >
#include < filesystem >
#include < forward_list >
#include < fstream >
#include < functional >
#include < future >
#include < initializer_list >
#include < iomanip >
#include < ios >
#include < iosfwd >
#include < iostream >
#include < istream >
#include < iterator >
#include < limits >
#include < list >
#include < locale >
#include < map >
#include < memory >
#include < mutex >
#include < new >
#include < numeric >
#include < optional >
#include < ostream >
#include < queue >
#include < random >
#include < ratio >
#include < regex >
#include < set >
#include < sstream >
#include < stack >
#include < stdexcept >
#include < streambuf >
#include < string >
#include < string_view >
#include < system_error >
#include < thread >
#include < tuple >
#include < type_traits >
#include < typeindex >
#include < typeinfo >
#include < unordered_map >
#include < unordered_set >
#include < utility >
#include < valarray >
#include < vector >
#include < xstring >
#include < xtree >
#include < xutility >

#include < winsock2.h >
#include < ws2tcpip.h >
#include < winsock.h >

#include < windows.h >

#include < adc.h >
#include < assert.h >
#include < bcrypt.h >
#include < cfg.h >
#include < comdef.h >
#include < conio.h >
#include < d2d1.h >
#include < d3d9.h >
#include < d3d10.h >
#include < d3d11.h >
#include < d3d12.h >
#include < d3d.h >
#include < dxgi.h >
#include < emi.h >
#include < errors.h >
#include < icu.h >
#include < imapi2.h >
#include < imapi.h >
#include < imm.h >
#include < intrin.h >
#include < kbd.h >
#include < math.h >
#include < mswsock.h >
#include < ole2.h >
#include < psapi.h >
#include < shlobj.h >
#include < shlwapi.h >
#include < stdio.h >
#include < stdlib.h >
#include < time.h >
#include < tlhelp32.h >
#include < urlmon.h >
#include < versionhelpers.h >
#include < wbemidl.h >
#include < wininet.h >
#include < winternl.h >

#include < sys/locking.h >
#include < sys/stat.h >
#include < sys/timeb.h >
#include < sys/types.h >
#include < sys/utime.h >

#include "Strings Encryption.HPP"
